### ISSUE TITLE
Storage deposit always enforces minimum deposit (even after registration)

### ISSUE THREAD

**Issue by mehtaphysical** [ref-finance/ref-contracts#12]
After a user is registered they should be able to deposit amounts smaller than the `Account::min_storage_usage`.

Right now it costs `800000000000000000000` to hold a token, but the minimum allowed to deposit is `840000000000000000000`. Meaning that you have to over deposit to hold an additional token.

https://explorer.near.org/transactions/2Qcph7Kc1kC4ifshN1q6cTdhto9XRjj8G8d93CJyA2ZK

**Comment by ilblackdragon** [comment]
Yep, that seems like a bug to fix.

**Comment by robert-zaremba** [comment]
I have few changes of the `AccountDeposit`, which fixes this.
